// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AtestadosECertidoesDocumentDataSlicesSlice = LinkDeDownloadSlice;

/**
 * Content for Atestados e Certidões documents
 */
interface AtestadosECertidoesDocumentData {
  /**
   * Título field in *Atestados e Certidões*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Atestados e Certidões
   * - **API ID Path**: atestados_e_certidoes.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Subtítulo field in *Atestados e Certidões*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Múltiplos parágrafos e marcações básicas
   * - **API ID Path**: atestados_e_certidoes.subtitulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Texto e link para o SICAF field in *Atestados e Certidões*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: ex: Clique aqui para consultar o SICAF
   * - **API ID Path**: atestados_e_certidoes.texto_e_link_para_o_sicaf
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto_e_link_para_o_sicaf: prismic.RichTextField;

  /**
   * Slice Zone field in *Atestados e Certidões*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: atestados_e_certidoes.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AtestadosECertidoesDocumentDataSlicesSlice> /**
   * Meta Title field in *Atestados e Certidões*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: atestados_e_certidoes.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Atestados e Certidões*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: atestados_e_certidoes.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Atestados e Certidões*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: atestados_e_certidoes.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Atestados e Certidões document from Prismic
 *
 * - **API ID**: `atestados_e_certidoes`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AtestadosECertidoesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AtestadosECertidoesDocumentData>,
    "atestados_e_certidoes",
    Lang
  >;

/**
 * Content for Colaborador documents
 */
interface ColaboradorDocumentData {
  /**
   * Foto field in *Colaborador*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: colaborador.foto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto: prismic.ImageField<"Tela estreita">;

  /**
   * Nome field in *Colaborador*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome e sobrenome (preferencialmente apenas 2)
   * - **API ID Path**: colaborador.nome
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;

  /**
   * Apresentação curta field in *Colaborador*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Parágrafo único
   * - **API ID Path**: colaborador.apresentacao_curta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  apresentacao_curta: prismic.RichTextField;

  /**
   * Apresentação longa field in *Colaborador*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: colaborador.apresentacao_longa
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  apresentacao_longa: prismic.RichTextField;

  /**
   * Ordem field in *Colaborador*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Valor maior ou igual a 1
   * - **API ID Path**: colaborador.ordem
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  ordem: prismic.NumberField;
}

/**
 * Colaborador document from Prismic
 *
 * - **API ID**: `colaborador`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ColaboradorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ColaboradorDocumentData>,
    "colaborador",
    Lang
  >;

type ColaboradoresDocumentDataSlicesSlice = never;

/**
 * Content for Colaboradores documents
 */
interface ColaboradoresDocumentData {
  /**
   * Título field in *Colaboradores*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Colaboradores
   * - **API ID Path**: colaboradores.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Slice Zone field in *Colaboradores*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: colaboradores.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ColaboradoresDocumentDataSlicesSlice> /**
   * Meta Title field in *Colaboradores*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: colaboradores.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Colaboradores*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: colaboradores.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Colaboradores*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: colaboradores.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Colaboradores document from Prismic
 *
 * - **API ID**: `colaboradores`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ColaboradoresDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ColaboradoresDocumentData>,
    "colaboradores",
    Lang
  >;

/**
 * Item in *Configurações → Navegação*
 */
export interface ConfiguracoesDocumentDataNavegacaoItem {
  /**
   * Link field in *Configurações → Navegação*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.navegacao[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Rótulo field in *Configurações → Navegação*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.navegacao[].rotulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  rotulo: prismic.KeyTextField;
}

type ConfiguracoesDocumentDataSlicesSlice = never;

/**
 * Content for Configurações documents
 */
interface ConfiguracoesDocumentData {
  /**
   * Nome do website field in *Configurações*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.nome_do_website
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_do_website: prismic.KeyTextField;

  /**
   * Meta-descrição field in *Configurações*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.metadescricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metadescricao: prismic.KeyTextField;

  /**
   * Imagem OG field in *Configurações*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.imagem_og
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_og: prismic.ImageField<never>;

  /**
   * Navegação field in *Configurações*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.navegacao[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navegacao: prismic.GroupField<
    Simplify<ConfiguracoesDocumentDataNavegacaoItem>
  >;

  /**
   * Logo field in *Configurações*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Configurações*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ConfiguracoesDocumentDataSlicesSlice> /**
   * Meta Title field in *Configurações*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: configuracoes.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Configurações*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: configuracoes.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Configurações*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Configurações document from Prismic
 *
 * - **API ID**: `configuracoes`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConfiguracoesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ConfiguracoesDocumentData>,
    "configuracoes",
    Lang
  >;

type ContatoDocumentDataSlicesSlice = FormaDeContatoSlice;

/**
 * Content for Contato documents
 */
interface ContatoDocumentData {
  /**
   * Título field in *Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Contato
   * - **API ID Path**: contato.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Mensagem de contato field in *Contato*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.mensagem_de_contato
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  mensagem_de_contato: prismic.RichTextField;

  /**
   * Foto do escritório field in *Contato*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.foto_do_escritorio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto_do_escritorio: prismic.ImageField<"Tela larga" | "Tela estreita">;

  /**
   * Link do Google Maps do escritório field in *Contato*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.link_do_google_maps_do_escritorio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_do_google_maps_do_escritorio: prismic.LinkField;

  /**
   * Slice Zone field in *Contato*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContatoDocumentDataSlicesSlice> /**
   * Meta Title field in *Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contato.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contato.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contato*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contato document from Prismic
 *
 * - **API ID**: `contato`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContatoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContatoDocumentData>,
    "contato",
    Lang
  >;

/**
 * Content for Depoimento documents
 */
interface DepoimentoDocumentData {
  /**
   * Texto field in *Depoimento*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto completo do depoimento da pessoa
   * - **API ID Path**: depoimento.texto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto: prismic.RichTextField;

  /**
   * Curso field in *Depoimento*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: ex: Plano de Contratações Anual - PCA: Da Implantação à Utilização
   * - **API ID Path**: depoimento.curso
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  curso: prismic.RichTextField;

  /**
   * Identificação do depoente field in *Depoimento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Luciana Verde Sub-secretária de Finanças
   * - **API ID Path**: depoimento.identificacao_do_depoente
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  identificacao_do_depoente: prismic.KeyTextField;

  /**
   * Local da organização field in *Depoimento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Município, estado, etc.
   * - **API ID Path**: depoimento.local_da_organizacao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  local_da_organizacao: prismic.KeyTextField;
}

/**
 * Depoimento document from Prismic
 *
 * - **API ID**: `depoimento`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DepoimentoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DepoimentoDocumentData>,
    "depoimento",
    Lang
  >;

type EventoDocumentDataSlicesSlice = CallToActionSlice;

/**
 * Content for Evento documents
 */
interface EventoDocumentData {
  /**
   * Imagem ilustrativa field in *Evento*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: evento.imagem_ilustrativa
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_ilustrativa: prismic.ImageField<
    "Tela larga" | "Tela estreita" | "Banner"
  >;

  /**
   * Nome do evento field in *Evento*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: ex: Alta Administração e Governança das Contratações: Responsabilidade e Desafio dos Gestores
   * - **API ID Path**: evento.nome_do_evento
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  nome_do_evento: prismic.RichTextField;

  /**
   * Valor do evento (curto) field in *Evento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: R$3.780,00
   * - **API ID Path**: evento.valor_do_evento
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  valor_do_evento: prismic.KeyTextField;

  /**
   * Conteúdo field in *Evento*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição do conteúdo do curso
   * - **API ID Path**: evento.conteudo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * Instrutor (curto) field in *Evento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Caso haja apenas um instrutor, preencher este campo
   * - **API ID Path**: evento.instrutor_curto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  instrutor_curto: prismic.KeyTextField;

  /**
   * Instrutores (longo) field in *Evento*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Preencher com os instrutores e suas credenciais
   * - **API ID Path**: evento.instrutores_longo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  instrutores_longo: prismic.RichTextField;

  /**
   * Público alvo field in *Evento*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição do público alvo do evento
   * - **API ID Path**: evento.publico_alvo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  publico_alvo: prismic.RichTextField;

  /**
   * Carga horária field in *Evento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: 4h
   * - **API ID Path**: evento.carga_horaria
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carga_horaria: prismic.KeyTextField;

  /**
   * Horário field in *Evento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: 08h às 16h
   * - **API ID Path**: evento.horario
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  horario: prismic.KeyTextField;

  /**
   * Data do evento field in *Evento*
   *
   * - **Field Type**: Date
   * - **Placeholder**: ex: 08/06/24
   * - **API ID Path**: evento.data_do_evento
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  data_do_evento: prismic.DateField;

  /**
   * Geolocalização field in *Evento*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: evento.geolocalizacao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  geolocalizacao: prismic.GeoPointField;

  /**
   * Link do evento field in *Evento*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: evento.link_do_evento
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_do_evento: prismic.LinkField;

  /**
   * Local do evento (curto) field in *Evento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Quixadá, CE
   * - **API ID Path**: evento.local_do_evento_curto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  local_do_evento_curto: prismic.KeyTextField;

  /**
   * Local do evento (longo) field in *Evento*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: evento.local_do_evento_longo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  local_do_evento_longo: prismic.RichTextField;

  /**
   * Valor do evento (longo) field in *Evento*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: ex: até 2 pessoas R$500. 3 a 5 pessoas...
   * - **API ID Path**: evento.valor_do_evento_longo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  valor_do_evento_longo: prismic.RichTextField;

  /**
   * Subtítulo do evento field in *Evento*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Parágrafo único
   * - **API ID Path**: evento.subtitulo_do_evento
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo_do_evento: prismic.RichTextField;

  /**
   * Slice Zone field in *Evento*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: evento.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EventoDocumentDataSlicesSlice> /**
   * Meta Title field in *Evento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: evento.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Evento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: evento.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Evento*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: evento.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Evento document from Prismic
 *
 * - **API ID**: `evento`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EventoDocumentData>, "evento", Lang>;

type InicioDocumentDataSlicesSlice =
  | CallToActionSlice
  | SecaoDepoimentosSlice
  | SecaoEventosSlice
  | SecaoConquistasSlice
  | SecaoCursosSlice
  | SecaoDeDestaqueSlice;

/**
 * Content for Início documents
 */
interface InicioDocumentData {
  /**
   * Título field in *Início*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: inicio.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Slice Zone field in *Início*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: inicio.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<InicioDocumentDataSlicesSlice> /**
   * Meta Title field in *Início*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: inicio.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Início*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: inicio.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Início*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: inicio.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Início document from Prismic
 *
 * - **API ID**: `inicio`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InicioDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<InicioDocumentData>,
    "inicio",
    Lang
  >;

type ModuloOuCursoDocumentDataSlicesSlice = CallToActionSlice;

/**
 * Content for Módulo ou Curso documents
 */
interface ModuloOuCursoDocumentData {
  /**
   * Título da página field in *Módulo ou Curso*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Também indica o tipo de página: "Módulo" ou "Curso"
   * - **API ID Path**: modulo_ou_curso.titulo_da_pagina
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  titulo_da_pagina: prismic.SelectField<"Módulo" | "Curso">;

  /**
   * Título do curso ou módulo field in *Módulo ou Curso*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: modulo_ou_curso.titulo_do_curso_ou_modulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo_do_curso_ou_modulo: prismic.RichTextField;

  /**
   * Imagem ilustrativa field in *Módulo ou Curso*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: modulo_ou_curso.imagem_ilustrativa
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_ilustrativa: prismic.ImageField<
    "Tela larga" | "Tela estreita" | "Banner"
  >;

  /**
   * Público-alvo field in *Módulo ou Curso*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Um ou mais parágrafos
   * - **API ID Path**: modulo_ou_curso.publico_alvo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  publico_alvo: prismic.RichTextField;

  /**
   * Investimento (curto) field in *Módulo ou Curso*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: a partir de R$3.780,00
   * - **API ID Path**: modulo_ou_curso.investimento_curto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  investimento_curto: prismic.KeyTextField;

  /**
   * Investimento (longo) field in *Módulo ou Curso*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Um ou mais parágrafos
   * - **API ID Path**: modulo_ou_curso.investimento_longo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  investimento_longo: prismic.RichTextField;

  /**
   * Carga horária field in *Módulo ou Curso*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: 4h
   * - **API ID Path**: modulo_ou_curso.carga_horaria
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carga_horaria: prismic.KeyTextField;

  /**
   * Instrutor (curto) field in *Módulo ou Curso*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Me. Ricardo Dias
   * - **API ID Path**: modulo_ou_curso.instrutor_curto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  instrutor_curto: prismic.KeyTextField;

  /**
   * Instrutores (longo) field in *Módulo ou Curso*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Listagem dos instrutores e suas credenciais
   * - **API ID Path**: modulo_ou_curso.instrutores_longo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  instrutores_longo: prismic.RichTextField;

  /**
   * Conteúdo field in *Módulo ou Curso*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Um ou mais parágrafos
   * - **API ID Path**: modulo_ou_curso.conteudo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * Subtítulo do módulo ou curso field in *Módulo ou Curso*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Parágrafo único
   * - **API ID Path**: modulo_ou_curso.subtitulo_do_modulo_ou_curso
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo_do_modulo_ou_curso: prismic.RichTextField;

  /**
   * Link para o módulo ou curso field in *Módulo ou Curso*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Redireciona do Card para a página do módulo ou curso
   * - **API ID Path**: modulo_ou_curso.link_para_o_modulo_ou_curso
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_para_o_modulo_ou_curso: prismic.LinkField;

  /**
   * Slice Zone field in *Módulo ou Curso*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: modulo_ou_curso.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ModuloOuCursoDocumentDataSlicesSlice> /**
   * Meta Title field in *Módulo ou Curso*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: modulo_ou_curso.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Módulo ou Curso*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: modulo_ou_curso.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Módulo ou Curso*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: modulo_ou_curso.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Módulo ou Curso document from Prismic
 *
 * - **API ID**: `modulo_ou_curso`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ModuloOuCursoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ModuloOuCursoDocumentData>,
    "modulo_ou_curso",
    Lang
  >;

type ModulosECursosDocumentDataSlicesSlice = CallToActionSlice;

/**
 * Content for Módulos e Cursos documents
 */
interface ModulosECursosDocumentData {
  /**
   * Título da página field in *Módulos e Cursos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Cursos e Módulos
   * - **API ID Path**: modulos_e_cursos.titulo_da_pagina
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_da_pagina: prismic.KeyTextField;

  /**
   * Texto-descrição da página field in *Módulos e Cursos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Um ou mais parágrafos
   * - **API ID Path**: modulos_e_cursos.texto_descricao_da_pagina
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto_descricao_da_pagina: prismic.RichTextField;

  /**
   * Título da seção "Cursos" field in *Módulos e Cursos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Cursos
   * - **API ID Path**: modulos_e_cursos.titulo_da_secao_cursos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_da_secao_cursos: prismic.KeyTextField;

  /**
   * Texto da seção "Cursos" field in *Módulos e Cursos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Um ou mais parágrafos
   * - **API ID Path**: modulos_e_cursos.texto_da_secao_cursos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto_da_secao_cursos: prismic.RichTextField;

  /**
   * Título da seção "Módulos" field in *Módulos e Cursos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: "Módulos"
   * - **API ID Path**: modulos_e_cursos.titulo_da_secao_modulos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_da_secao_modulos: prismic.KeyTextField;

  /**
   * Texto da seção "Módulos" field in *Módulos e Cursos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Um ou mais parágrafos
   * - **API ID Path**: modulos_e_cursos.texto_da_secao_modulos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto_da_secao_modulos: prismic.RichTextField;

  /**
   * Slice Zone field in *Módulos e Cursos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: modulos_e_cursos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ModulosECursosDocumentDataSlicesSlice> /**
   * Meta Title field in *Módulos e Cursos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: modulos_e_cursos.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Módulos e Cursos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: modulos_e_cursos.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Módulos e Cursos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: modulos_e_cursos.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Módulos e Cursos document from Prismic
 *
 * - **API ID**: `modulos_e_cursos`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ModulosECursosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ModulosECursosDocumentData>,
    "modulos_e_cursos",
    Lang
  >;

type NossosClientesDocumentDataSlicesSlice = CardDeClientSlice;

/**
 * Content for Nossos clientes documents
 */
interface NossosClientesDocumentData {
  /**
   * Título field in *Nossos clientes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Nossos clientes
   * - **API ID Path**: nossos_clientes.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Descrição da página field in *Nossos clientes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nossos_clientes.descricao_da_pagina
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao_da_pagina: prismic.RichTextField;

  /**
   * Imagem ilustrativa field in *Nossos clientes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nossos_clientes.imagem_ilustrativa
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_ilustrativa: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Nossos clientes*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nossos_clientes.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NossosClientesDocumentDataSlicesSlice> /**
   * Meta Title field in *Nossos clientes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: nossos_clientes.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Nossos clientes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: nossos_clientes.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Nossos clientes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nossos_clientes.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Nossos clientes document from Prismic
 *
 * - **API ID**: `nossos_clientes`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NossosClientesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NossosClientesDocumentData>,
    "nossos_clientes",
    Lang
  >;

/**
 * Item in *Próximos Eventos → Eventos abertos*
 */
export interface ProximosEventosDocumentDataEventosAbertosItem {
  /**
   * Evento field in *Próximos Eventos → Eventos abertos*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: proximos_eventos.eventos_abertos[].evento
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  evento: prismic.ContentRelationshipField<"evento">;
}

type ProximosEventosDocumentDataSlicesSlice = CallToActionSlice;

/**
 * Content for Próximos Eventos documents
 */
interface ProximosEventosDocumentData {
  /**
   * Título da página field in *Próximos Eventos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Próximos eventos
   * - **API ID Path**: proximos_eventos.titulo_da_pagina
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_da_pagina: prismic.KeyTextField;

  /**
   * Texto da página field in *Próximos Eventos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Um ou mais parágrafos
   * - **API ID Path**: proximos_eventos.texto_da_pagina
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto_da_pagina: prismic.RichTextField;

  /**
   * Eventos abertos field in *Próximos Eventos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: proximos_eventos.eventos_abertos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  eventos_abertos: prismic.GroupField<
    Simplify<ProximosEventosDocumentDataEventosAbertosItem>
  >;

  /**
   * Slice Zone field in *Próximos Eventos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: proximos_eventos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProximosEventosDocumentDataSlicesSlice> /**
   * Meta Title field in *Próximos Eventos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: proximos_eventos.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Próximos Eventos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: proximos_eventos.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Próximos Eventos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: proximos_eventos.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Próximos Eventos document from Prismic
 *
 * - **API ID**: `proximos_eventos`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProximosEventosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProximosEventosDocumentData>,
    "proximos_eventos",
    Lang
  >;

type QuemSomosDocumentDataSlicesSlice = never;

/**
 * Content for Quem somos documents
 */
interface QuemSomosDocumentData {
  /**
   * Título field in *Quem somos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Quem somos
   * - **API ID Path**: quem_somos.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Texto de apresentação field in *Quem somos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto longo de apresentação da empresa
   * - **API ID Path**: quem_somos.texto_de_apresentacao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto_de_apresentacao: prismic.RichTextField;

  /**
   * Propósito field in *Quem somos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto sobre o propósito
   * - **API ID Path**: quem_somos.proposito
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  proposito: prismic.RichTextField;

  /**
   * Missão field in *Quem somos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto da missão da empresa
   * - **API ID Path**: quem_somos.missao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  missao: prismic.RichTextField;

  /**
   * Visão field in *Quem somos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto da visão da empresa
   * - **API ID Path**: quem_somos.visao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  visao: prismic.RichTextField;

  /**
   * Vídeo field in *Quem somos*
   *
   * - **Field Type**: Link
   * - **Placeholder**: URL de incorporação do Youtube
   * - **API ID Path**: quem_somos.video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField;

  /**
   * Slice Zone field in *Quem somos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: quem_somos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<QuemSomosDocumentDataSlicesSlice> /**
   * Meta Title field in *Quem somos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: quem_somos.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Quem somos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: quem_somos.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Quem somos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quem_somos.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Quem somos document from Prismic
 *
 * - **API ID**: `quem_somos`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type QuemSomosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<QuemSomosDocumentData>,
    "quem_somos",
    Lang
  >;

export type AllDocumentTypes =
  | AtestadosECertidoesDocument
  | ColaboradorDocument
  | ColaboradoresDocument
  | ConfiguracoesDocument
  | ContatoDocument
  | DepoimentoDocument
  | EventoDocument
  | InicioDocument
  | ModuloOuCursoDocument
  | ModulosECursosDocument
  | NossosClientesDocument
  | ProximosEventosDocument
  | QuemSomosDocument;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Texto CTA field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto mais extenso da chamada à ação (call to action)
   * - **API ID Path**: call_to_action.default.primary.texto_cta
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto_cta: prismic.RichTextField;

  /**
   * Texto do botão CTA field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.texto_do_botao_cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texto_do_botao_cta: prismic.KeyTextField;

  /**
   * Link do CTA field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.link_do_cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_do_cta: prismic.LinkField;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *CardDeCliente → Default → Primary*
 */
export interface CardDeClientSliceDefaultPrimary {
  /**
   * Logo do cliente field in *CardDeCliente → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_de_client.default.primary.logo_do_cliente
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_do_cliente: prismic.ImageField<"Tela estreita" | "Tela larga">;

  /**
   * Nome do cliente field in *CardDeCliente → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Prefeitura de Varjota
   * - **API ID Path**: card_de_client.default.primary.nome_do_cliente
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_do_cliente: prismic.KeyTextField;
}

/**
 * Default variation for CardDeCliente Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardDeClientSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardDeClientSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CardDeCliente*
 */
type CardDeClientSliceVariation = CardDeClientSliceDefault;

/**
 * CardDeCliente Shared Slice
 *
 * - **API ID**: `card_de_client`
 * - **Description**: CardDeClient
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardDeClientSlice = prismic.SharedSlice<
  "card_de_client",
  CardDeClientSliceVariation
>;

/**
 * Primary content in *FormaDeContato → Default → Primary*
 */
export interface FormaDeContatoSliceDefaultPrimary {
  /**
   * Ícone field in *FormaDeContato → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: forma_de_contato.default.primary.icone
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icone: prismic.SelectField<"Instagram" | "WhatsApp" | "E-mail" | "Endereço">;

  /**
   * Texto field in *FormaDeContato → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: ex: @practicustc
   * - **API ID Path**: forma_de_contato.default.primary.texto
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto: prismic.RichTextField;
}

/**
 * Default variation for FormaDeContato Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormaDeContatoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormaDeContatoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FormaDeContato*
 */
type FormaDeContatoSliceVariation = FormaDeContatoSliceDefault;

/**
 * FormaDeContato Shared Slice
 *
 * - **API ID**: `forma_de_contato`
 * - **Description**: FormaDeContato
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormaDeContatoSlice = prismic.SharedSlice<
  "forma_de_contato",
  FormaDeContatoSliceVariation
>;

/**
 * Primary content in *LinkDeDownload → Default → Primary*
 */
export interface LinkDeDownloadSliceDefaultPrimary {
  /**
   * Nome do arquivo field in *LinkDeDownload → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_de_download.default.primary.nome_do_arquivo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_do_arquivo: prismic.KeyTextField;

  /**
   * Arquivo field in *LinkDeDownload → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: link_de_download.default.primary.arquivo
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  arquivo: prismic.LinkToMediaField;
}

/**
 * Default variation for LinkDeDownload Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkDeDownloadSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkDeDownloadSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LinkDeDownload*
 */
type LinkDeDownloadSliceVariation = LinkDeDownloadSliceDefault;

/**
 * LinkDeDownload Shared Slice
 *
 * - **API ID**: `link_de_download`
 * - **Description**: LinkDeDownload
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkDeDownloadSlice = prismic.SharedSlice<
  "link_de_download",
  LinkDeDownloadSliceVariation
>;

/**
 * Primary content in *SecaoConquistas → Default → Primary*
 */
export interface SecaoConquistasSliceDefaultPrimary {
  /**
   * Imagem das conquistas field in *SecaoConquistas → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_conquistas.default.primary.imagem_das_conquistas
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_das_conquistas: prismic.ImageField<"Tela estreita" | "Tela larga">;

  /**
   * Título da seção field in *SecaoConquistas → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_conquistas.default.primary.titulo_da_secao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_da_secao: prismic.KeyTextField;
}

/**
 * Default variation for SecaoConquistas Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecaoConquistasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SecaoConquistasSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SecaoConquistas*
 */
type SecaoConquistasSliceVariation = SecaoConquistasSliceDefault;

/**
 * SecaoConquistas Shared Slice
 *
 * - **API ID**: `secao_conquistas`
 * - **Description**: SecaoConquistas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecaoConquistasSlice = prismic.SharedSlice<
  "secao_conquistas",
  SecaoConquistasSliceVariation
>;

/**
 * Primary content in *SecaoCursos → Default → Primary*
 */
export interface SecaoCursosSliceDefaultPrimary {
  /**
   * Imagem de fundo field in *SecaoCursos → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_cursos.default.primary.imagem_de_fundo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_de_fundo: prismic.ImageField<"Telas largas" | "Telas estreitas">;

  /**
   * Texto do botão field in *SecaoCursos → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_cursos.default.primary.texto_do_botao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texto_do_botao: prismic.KeyTextField;

  /**
   * Link do botão field in *SecaoCursos → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_cursos.default.primary.link_do_botao
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_do_botao: prismic.LinkField;

  /**
   * Título da seção field in *SecaoCursos → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_cursos.default.primary.titulo_da_secao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_da_secao: prismic.KeyTextField;

  /**
   * Texto sobre imagem field in *SecaoCursos → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Pode ser vazio
   * - **API ID Path**: secao_cursos.default.primary.texto_sobre_imagem
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto_sobre_imagem: prismic.RichTextField;
}

/**
 * Default variation for SecaoCursos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecaoCursosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SecaoCursosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SecaoCursos*
 */
type SecaoCursosSliceVariation = SecaoCursosSliceDefault;

/**
 * SecaoCursos Shared Slice
 *
 * - **API ID**: `secao_cursos`
 * - **Description**: SecaoCursos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecaoCursosSlice = prismic.SharedSlice<
  "secao_cursos",
  SecaoCursosSliceVariation
>;

/**
 * Primary content in *SecaoDeDestaque → Default → Primary*
 */
export interface SecaoDeDestaqueSliceDefaultPrimary {
  /**
   * Banner field in *SecaoDeDestaque → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_de_destaque.default.primary.banner
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<"Tela larga" | "Tela estreita">;
}

/**
 * Default variation for SecaoDeDestaque Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecaoDeDestaqueSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SecaoDeDestaqueSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SecaoDeDestaque*
 */
type SecaoDeDestaqueSliceVariation = SecaoDeDestaqueSliceDefault;

/**
 * SecaoDeDestaque Shared Slice
 *
 * - **API ID**: `secao_de_destaque`
 * - **Description**: SecaoDeDestaque
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecaoDeDestaqueSlice = prismic.SharedSlice<
  "secao_de_destaque",
  SecaoDeDestaqueSliceVariation
>;

/**
 * Item in *SecaoDepoimentos → Default → Primary → Depoimentos*
 */
export interface SecaoDepoimentosSliceDefaultPrimaryDepoimentoItem {
  /**
   * Depoimento field in *SecaoDepoimentos → Default → Primary → Depoimentos*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_depoimentos.default.primary.depoimento[].depoimento
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  depoimento: prismic.ContentRelationshipField;
}

/**
 * Primary content in *SecaoDepoimentos → Default → Primary*
 */
export interface SecaoDepoimentosSliceDefaultPrimary {
  /**
   * Depoimentos field in *SecaoDepoimentos → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_depoimentos.default.primary.depoimento[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  depoimento: prismic.GroupField<
    Simplify<SecaoDepoimentosSliceDefaultPrimaryDepoimentoItem>
  >;

  /**
   * Título da seção field in *SecaoDepoimentos → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_depoimentos.default.primary.titulo_da_secao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_da_secao: prismic.KeyTextField;
}

/**
 * Default variation for SecaoDepoimentos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecaoDepoimentosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SecaoDepoimentosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SecaoDepoimentos*
 */
type SecaoDepoimentosSliceVariation = SecaoDepoimentosSliceDefault;

/**
 * SecaoDepoimentos Shared Slice
 *
 * - **API ID**: `secao_depoimentos`
 * - **Description**: SecaoDepoimentos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecaoDepoimentosSlice = prismic.SharedSlice<
  "secao_depoimentos",
  SecaoDepoimentosSliceVariation
>;

/**
 * Item in *SecaoEventos → Default → Primary → Eventos*
 */
export interface SecaoEventosSliceDefaultPrimaryEventosItem {
  /**
   * Evento field in *SecaoEventos → Default → Primary → Eventos*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_eventos.default.primary.eventos[].evento
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  evento: prismic.ContentRelationshipField;
}

/**
 * Primary content in *SecaoEventos → Default → Primary*
 */
export interface SecaoEventosSliceDefaultPrimary {
  /**
   * Eventos field in *SecaoEventos → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_eventos.default.primary.eventos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  eventos: prismic.GroupField<
    Simplify<SecaoEventosSliceDefaultPrimaryEventosItem>
  >;

  /**
   * Título da seção field in *SecaoEventos → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_eventos.default.primary.titulo_da_secao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_da_secao: prismic.KeyTextField;
}

/**
 * Default variation for SecaoEventos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecaoEventosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SecaoEventosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SecaoEventos*
 */
type SecaoEventosSliceVariation = SecaoEventosSliceDefault;

/**
 * SecaoEventos Shared Slice
 *
 * - **API ID**: `secao_eventos`
 * - **Description**: SecaoEventos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecaoEventosSlice = prismic.SharedSlice<
  "secao_eventos",
  SecaoEventosSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AtestadosECertidoesDocument,
      AtestadosECertidoesDocumentData,
      AtestadosECertidoesDocumentDataSlicesSlice,
      ColaboradorDocument,
      ColaboradorDocumentData,
      ColaboradoresDocument,
      ColaboradoresDocumentData,
      ColaboradoresDocumentDataSlicesSlice,
      ConfiguracoesDocument,
      ConfiguracoesDocumentData,
      ConfiguracoesDocumentDataNavegacaoItem,
      ConfiguracoesDocumentDataSlicesSlice,
      ContatoDocument,
      ContatoDocumentData,
      ContatoDocumentDataSlicesSlice,
      DepoimentoDocument,
      DepoimentoDocumentData,
      EventoDocument,
      EventoDocumentData,
      EventoDocumentDataSlicesSlice,
      InicioDocument,
      InicioDocumentData,
      InicioDocumentDataSlicesSlice,
      ModuloOuCursoDocument,
      ModuloOuCursoDocumentData,
      ModuloOuCursoDocumentDataSlicesSlice,
      ModulosECursosDocument,
      ModulosECursosDocumentData,
      ModulosECursosDocumentDataSlicesSlice,
      NossosClientesDocument,
      NossosClientesDocumentData,
      NossosClientesDocumentDataSlicesSlice,
      ProximosEventosDocument,
      ProximosEventosDocumentData,
      ProximosEventosDocumentDataEventosAbertosItem,
      ProximosEventosDocumentDataSlicesSlice,
      QuemSomosDocument,
      QuemSomosDocumentData,
      QuemSomosDocumentDataSlicesSlice,
      AllDocumentTypes,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CardDeClientSlice,
      CardDeClientSliceDefaultPrimary,
      CardDeClientSliceVariation,
      CardDeClientSliceDefault,
      FormaDeContatoSlice,
      FormaDeContatoSliceDefaultPrimary,
      FormaDeContatoSliceVariation,
      FormaDeContatoSliceDefault,
      LinkDeDownloadSlice,
      LinkDeDownloadSliceDefaultPrimary,
      LinkDeDownloadSliceVariation,
      LinkDeDownloadSliceDefault,
      SecaoConquistasSlice,
      SecaoConquistasSliceDefaultPrimary,
      SecaoConquistasSliceVariation,
      SecaoConquistasSliceDefault,
      SecaoCursosSlice,
      SecaoCursosSliceDefaultPrimary,
      SecaoCursosSliceVariation,
      SecaoCursosSliceDefault,
      SecaoDeDestaqueSlice,
      SecaoDeDestaqueSliceDefaultPrimary,
      SecaoDeDestaqueSliceVariation,
      SecaoDeDestaqueSliceDefault,
      SecaoDepoimentosSlice,
      SecaoDepoimentosSliceDefaultPrimaryDepoimentoItem,
      SecaoDepoimentosSliceDefaultPrimary,
      SecaoDepoimentosSliceVariation,
      SecaoDepoimentosSliceDefault,
      SecaoEventosSlice,
      SecaoEventosSliceDefaultPrimaryEventosItem,
      SecaoEventosSliceDefaultPrimary,
      SecaoEventosSliceVariation,
      SecaoEventosSliceDefault,
    };
  }
}
