export const PUBLIC_AGENT_OCCUPATIONS = [
  "PREFEITO",
  "VICE-PREFEITO",
  "PRESIDENTE DE CÃMARA",
  "VEREADOR",
  "SECRETÁRIO MUNICIPAL",
  "PROCURADOR",
  "ASSESOR JURÍDICO",
  "CONTROLADOR",
  "MEMBRO DO CONTROLE INTERNO",
  "AGENTE DE CONTRATAÇÃO",
  "MEMBRO DE APOIO À LICITAÇÃO",
  "MEMBRO DE APOIO AO PLANEJAMENTO",
  "GESTOR DE CONTRATO",
  "FISCAL DE CONTRATO",
];

export const PRIVATE_AGENT_OCCUPATIONS = [
  "ASSESSOR DE CONSULTORIA EM LICITAÇÕES",
  "REPRESENTANTE/PROPRIETÁRIO DE EMPRESA LICITANTE",
  "ESTAGIÁRIO",
];

export const HOW_DID_YOU_HEAR_ABOUT_US_OPTIONS = [
  "INSTAGRAM",
  "SITE",
  "JÁ CONHECIA POR OUTRA CAPACITAÇÃO",
  "FUI INDICADO(A) POR OUTRA PESSOA",
  "OUTRO",
];
